set identity_insert [TYPE] on

merge into [TYPE] as T using
	(values

		(1, 1, 'Vrijstaande boerderij Zuivelhof. Opp. 192 m². Vierslaapkamers. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 3 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 1),
		(2, 2, 'Cottage Chantal. Een 6-persoons luxe cottages opp. 72m2 met grote woonkamer met design Hoekbank, flatscreen TV 60”, open haard, homecinema met DVD-speler, luxe keuken met oven, magnetron en vaatwasser. In de badkamer heeft u de beschikking over een douche, bad, infrarood sauna en een whirlpool.  Schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet. Maximaal 1 auto  kan voor uw luxe cottage geparkeerd worden of u kunt gebruik maken van Valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 1),
		(3, 3, 'Landhuizen Debora (350 m².) Pas gerenoveerde landhuizen, gelegen in een bevoorrechte positie in ons park. Omgeven door olijfbomen heeft een omheinde tuin van 250 vierkante meter. gemeubileerd en superieure met zwembad, pizza-oven en barbecue. De gebieden in de zon op het gazon zijn een leuke solarium zijn beschikbaar ligstoelen en ligbedden, terwijl de grijze gedeelten van bomen of paraplu zijn geschikt voor ontspanning en lezen. een veranda (18 m².) is uitgerust om buiten te eten. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 9 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking.  Uiteraard zijn alle diensten 24/7 beschikbaar', 1),
		(4, 4, 'Zeer grote (en lange) vakantiewoning (Opp. 18000m2) voor grote groepen. Deze  vakantievilla behoord tot de meest bijzondere gebouwen van ons park. Door de lengte van de villa ervaart u een extra ruimtelijk gevoel. Zeer geschikt als u met uw vrienden of gehele familie graag bij elkaar bent.  Er zijn binnen u villa twee golfslagbaden , een theater, een bioscoop en een door Erich zu Putlitz ontworpen feestzaal met veel zitplaatsen. Aan een kade is ruimte om uw eigen boot af te meren. ', 1),
		
		(5, 1, 'Vrijstaande boerderij Zuivelhof. Opp. 192 m². Vierslaapkamers. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 3 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 2),
		(6, 2, 'Cottage Chantal. Een 6-persoons luxe cottages opp. 72m2 met grote woonkamer met design Hoekbank, flatscreen TV 60”, open haard, homecinema met DVD-speler, luxe keuken met oven, magnetron en vaatwasser. In de badkamer heeft u de beschikking over een douche, bad, infrarood sauna en een whirlpool.  Schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet. Maximaal 1 auto  kan voor uw luxe cottage geparkeerd worden of u kunt gebruik maken van Valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 2),
		(7, 3, 'Landhuizen Debora (350 m².) Pas gerenoveerde landhuizen, gelegen in een bevoorrechte positie in ons park. Omgeven door olijfbomen heeft een omheinde tuin van 250 vierkante meter. gemeubileerd en superieure met zwembad, pizza-oven en barbecue. De gebieden in de zon op het gazon zijn een leuke solarium zijn beschikbaar ligstoelen en ligbedden, terwijl de grijze gedeelten van bomen of paraplu zijn geschikt voor ontspanning en lezen. een veranda (18 m².) is uitgerust om buiten te eten. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 9 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking.  Uiteraard zijn alle diensten 24/7 beschikbaar', 2),
		(8, 4, 'Zeer grote (en lange) vakantiewoning (Opp. 18000m2) voor grote groepen. Deze  vakantievilla behoord tot de meest bijzondere gebouwen van ons park. Door de lengte van de villa ervaart u een extra ruimtelijk gevoel. Zeer geschikt als u met uw vrienden of gehele familie graag bij elkaar bent.  Er zijn binnen u villa twee golfslagbaden , een theater, een bioscoop en een door Erich zu Putlitz ontworpen feestzaal met veel zitplaatsen. Aan een kade is ruimte om uw eigen boot af te meren. ', 2),
	
	(9, 1, 'Vrijstaande boerderij Zuivelhof. Opp. 192 m². Vierslaapkamers. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 3 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 3),
		(10, 2, 'Cottage Chantal. Een 6-persoons luxe cottages opp. 72m2 met grote woonkamer met design Hoekbank, flatscreen TV 60”, open haard, homecinema met DVD-speler, luxe keuken met oven, magnetron en vaatwasser. In de badkamer heeft u de beschikking over een douche, bad, infrarood sauna en een whirlpool.  Schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet. Maximaal 1 auto  kan voor uw luxe cottage geparkeerd worden of u kunt gebruik maken van Valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 3),
		(11, 3, 'Landhuizen Debora (350 m².) Pas gerenoveerde landhuizen, gelegen in een bevoorrechte positie in ons park. Omgeven door olijfbomen heeft een omheinde tuin van 250 vierkante meter. gemeubileerd en superieure met zwembad, pizza-oven en barbecue. De gebieden in de zon op het gazon zijn een leuke solarium zijn beschikbaar ligstoelen en ligbedden, terwijl de grijze gedeelten van bomen of paraplu zijn geschikt voor ontspanning en lezen. een veranda (18 m².) is uitgerust om buiten te eten. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 9 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking.  Uiteraard zijn alle diensten 24/7 beschikbaar', 3),
		(12, 4, 'Zeer grote (en lange) vakantiewoning (Opp. 18000m2) voor grote groepen. Deze  vakantievilla behoord tot de meest bijzondere gebouwen van ons park. Door de lengte van de villa ervaart u een extra ruimtelijk gevoel. Zeer geschikt als u met uw vrienden of gehele familie graag bij elkaar bent.  Er zijn binnen u villa twee golfslagbaden , een theater, een bioscoop en een door Erich zu Putlitz ontworpen feestzaal met veel zitplaatsen. Aan een kade is ruimte om uw eigen boot af te meren. ', 3),
	
	(13, 1, 'Vrijstaande boerderij Zuivelhof. Opp. 192 m². Vierslaapkamers. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 3 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 4),
		(14, 2, 'Cottage Chantal. Een 6-persoons luxe cottages opp. 72m2 met grote woonkamer met design Hoekbank, flatscreen TV 60”, open haard, homecinema met DVD-speler, luxe keuken met oven, magnetron en vaatwasser. In de badkamer heeft u de beschikking over een douche, bad, infrarood sauna en een whirlpool.  Schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet. Maximaal 1 auto  kan voor uw luxe cottage geparkeerd worden of u kunt gebruik maken van Valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 4),
		(15, 3, 'Landhuizen Debora (350 m².) Pas gerenoveerde landhuizen, gelegen in een bevoorrechte positie in ons park. Omgeven door olijfbomen heeft een omheinde tuin van 250 vierkante meter. gemeubileerd en superieure met zwembad, pizza-oven en barbecue. De gebieden in de zon op het gazon zijn een leuke solarium zijn beschikbaar ligstoelen en ligbedden, terwijl de grijze gedeelten van bomen of paraplu zijn geschikt voor ontspanning en lezen. een veranda (18 m².) is uitgerust om buiten te eten. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 9 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking.  Uiteraard zijn alle diensten 24/7 beschikbaar', 4),
		(16, 4, 'Zeer grote (en lange) vakantiewoning (Opp. 18000m2) voor grote groepen. Deze  vakantievilla behoord tot de meest bijzondere gebouwen van ons park. Door de lengte van de villa ervaart u een extra ruimtelijk gevoel. Zeer geschikt als u met uw vrienden of gehele familie graag bij elkaar bent.  Er zijn binnen u villa twee golfslagbaden , een theater, een bioscoop en een door Erich zu Putlitz ontworpen feestzaal met veel zitplaatsen. Aan een kade is ruimte om uw eigen boot af te meren. ', 4),
	
	(17, 1, 'Vrijstaande boerderij Zuivelhof. Opp. 192 m². Vierslaapkamers. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 3 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 5),
		(18, 2, 'Cottage Chantal. Een 6-persoons luxe cottages opp. 72m2 met grote woonkamer met design Hoekbank, flatscreen TV 60”, open haard, homecinema met DVD-speler, luxe keuken met oven, magnetron en vaatwasser. In de badkamer heeft u de beschikking over een douche, bad, infrarood sauna en een whirlpool.  Schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet. Maximaal 1 auto  kan voor uw luxe cottage geparkeerd worden of u kunt gebruik maken van Valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 5),
		(19, 3, 'Landhuizen Debora (350 m².) Pas gerenoveerde landhuizen, gelegen in een bevoorrechte positie in ons park. Omgeven door olijfbomen heeft een omheinde tuin van 250 vierkante meter. gemeubileerd en superieure met zwembad, pizza-oven en barbecue. De gebieden in de zon op het gazon zijn een leuke solarium zijn beschikbaar ligstoelen en ligbedden, terwijl de grijze gedeelten van bomen of paraplu zijn geschikt voor ontspanning en lezen. een veranda (18 m².) is uitgerust om buiten te eten. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 9 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking.  Uiteraard zijn alle diensten 24/7 beschikbaar', 5),
		(20, 4, 'Zeer grote (en lange) vakantiewoning (Opp. 18000m2) voor grote groepen. Deze  vakantievilla behoord tot de meest bijzondere gebouwen van ons park. Door de lengte van de villa ervaart u een extra ruimtelijk gevoel. Zeer geschikt als u met uw vrienden of gehele familie graag bij elkaar bent.  Er zijn binnen u villa twee golfslagbaden , een theater, een bioscoop en een door Erich zu Putlitz ontworpen feestzaal met veel zitplaatsen. Aan een kade is ruimte om uw eigen boot af te meren. ', 5),
	

	(21, 1, 'Vrijstaande boerderij Zuivelhof. Opp. 192 m². Vierslaapkamers. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 3 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 6),
		(22, 2, 'Cottage Chantal. Een 6-persoons luxe cottages opp. 72m2 met grote woonkamer met design Hoekbank, flatscreen TV 60”, open haard, homecinema met DVD-speler, luxe keuken met oven, magnetron en vaatwasser. In de badkamer heeft u de beschikking over een douche, bad, infrarood sauna en een whirlpool.  Schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet. Maximaal 1 auto  kan voor uw luxe cottage geparkeerd worden of u kunt gebruik maken van Valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 6),
		(23, 3, 'Landhuizen Debora (350 m².) Pas gerenoveerde landhuizen, gelegen in een bevoorrechte positie in ons park. Omgeven door olijfbomen heeft een omheinde tuin van 250 vierkante meter. gemeubileerd en superieure met zwembad, pizza-oven en barbecue. De gebieden in de zon op het gazon zijn een leuke solarium zijn beschikbaar ligstoelen en ligbedden, terwijl de grijze gedeelten van bomen of paraplu zijn geschikt voor ontspanning en lezen. een veranda (18 m².) is uitgerust om buiten te eten. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 9 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking.  Uiteraard zijn alle diensten 24/7 beschikbaar', 6),
		(24, 4, 'Zeer grote (en lange) vakantiewoning (Opp. 18000m2) voor grote groepen. Deze  vakantievilla behoord tot de meest bijzondere gebouwen van ons park. Door de lengte van de villa ervaart u een extra ruimtelijk gevoel. Zeer geschikt als u met uw vrienden of gehele familie graag bij elkaar bent.  Er zijn binnen u villa twee golfslagbaden , een theater, een bioscoop en een door Erich zu Putlitz ontworpen feestzaal met veel zitplaatsen. Aan een kade is ruimte om uw eigen boot af te meren. ', 6),
	
	(25, 1, 'Vrijstaande boerderij Zuivelhof. Opp. 192 m². Vierslaapkamers. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 3 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 7),
		(26, 2, 'Cottage Chantal. Een 6-persoons luxe cottages opp. 72m2 met grote woonkamer met design Hoekbank, flatscreen TV 60”, open haard, homecinema met DVD-speler, luxe keuken met oven, magnetron en vaatwasser. In de badkamer heeft u de beschikking over een douche, bad, infrarood sauna en een whirlpool.  Schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet. Maximaal 1 auto  kan voor uw luxe cottage geparkeerd worden of u kunt gebruik maken van Valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 7),
		(27, 3, 'Landhuizen Debora (350 m².) Pas gerenoveerde landhuizen, gelegen in een bevoorrechte positie in ons park. Omgeven door olijfbomen heeft een omheinde tuin van 250 vierkante meter. gemeubileerd en superieure met zwembad, pizza-oven en barbecue. De gebieden in de zon op het gazon zijn een leuke solarium zijn beschikbaar ligstoelen en ligbedden, terwijl de grijze gedeelten van bomen of paraplu zijn geschikt voor ontspanning en lezen. een veranda (18 m².) is uitgerust om buiten te eten. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 9 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking.  Uiteraard zijn alle diensten 24/7 beschikbaar', 7),
		(28, 4, 'Zeer grote (en lange) vakantiewoning (Opp. 18000m2) voor grote groepen. Deze  vakantievilla behoord tot de meest bijzondere gebouwen van ons park. Door de lengte van de villa ervaart u een extra ruimtelijk gevoel. Zeer geschikt als u met uw vrienden of gehele familie graag bij elkaar bent.  Er zijn binnen u villa twee golfslagbaden , een theater, een bioscoop en een door Erich zu Putlitz ontworpen feestzaal met veel zitplaatsen. Aan een kade is ruimte om uw eigen boot af te meren. ', 7),
	
	(29, 1, 'Vrijstaande boerderij Zuivelhof. Opp. 192 m². Vierslaapkamers. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 3 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 8),
		(30, 2, 'Cottage Chantal. Een 6-persoons luxe cottages opp. 72m2 met grote woonkamer met design Hoekbank, flatscreen TV 60”, open haard, homecinema met DVD-speler, luxe keuken met oven, magnetron en vaatwasser. In de badkamer heeft u de beschikking over een douche, bad, infrarood sauna en een whirlpool.  Schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet. Maximaal 1 auto  kan voor uw luxe cottage geparkeerd worden of u kunt gebruik maken van Valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 8),
		(31, 3, 'Landhuizen Debora (350 m².) Pas gerenoveerde landhuizen, gelegen in een bevoorrechte positie in ons park. Omgeven door olijfbomen heeft een omheinde tuin van 250 vierkante meter. gemeubileerd en superieure met zwembad, pizza-oven en barbecue. De gebieden in de zon op het gazon zijn een leuke solarium zijn beschikbaar ligstoelen en ligbedden, terwijl de grijze gedeelten van bomen of paraplu zijn geschikt voor ontspanning en lezen. een veranda (18 m².) is uitgerust om buiten te eten. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 9 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking.  Uiteraard zijn alle diensten 24/7 beschikbaar', 8),
		(32, 4, 'Zeer grote (en lange) vakantiewoning (Opp. 18000m2) voor grote groepen. Deze  vakantievilla behoord tot de meest bijzondere gebouwen van ons park. Door de lengte van de villa ervaart u een extra ruimtelijk gevoel. Zeer geschikt als u met uw vrienden of gehele familie graag bij elkaar bent.  Er zijn binnen u villa twee golfslagbaden , een theater, een bioscoop en een door Erich zu Putlitz ontworpen feestzaal met veel zitplaatsen. Aan een kade is ruimte om uw eigen boot af te meren. ', 8),
	
	(33, 1, 'Vrijstaande boerderij Zuivelhof. Opp. 192 m². Vierslaapkamers. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 3 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 9),
		(34, 2, 'Cottage Chantal. Een 6-persoons luxe cottages opp. 72m2 met grote woonkamer met design Hoekbank, flatscreen TV 60”, open haard, homecinema met DVD-speler, luxe keuken met oven, magnetron en vaatwasser. In de badkamer heeft u de beschikking over een douche, bad, infrarood sauna en een whirlpool.  Schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet. Maximaal 1 auto  kan voor uw luxe cottage geparkeerd worden of u kunt gebruik maken van Valet Parking. Uiteraard zijn alle diensten 24/7 beschikbaar.', 9),
		(35, 3, 'Landhuizen Debora (350 m².) Pas gerenoveerde landhuizen, gelegen in een bevoorrechte positie in ons park. Omgeven door olijfbomen heeft een omheinde tuin van 250 vierkante meter. gemeubileerd en superieure met zwembad, pizza-oven en barbecue. De gebieden in de zon op het gazon zijn een leuke solarium zijn beschikbaar ligstoelen en ligbedden, terwijl de grijze gedeelten van bomen of paraplu zijn geschikt voor ontspanning en lezen. een veranda (18 m².) is uitgerust om buiten te eten. Badkamer met infrarood sauna, whirlpool met handdouche en wastafel. Apart toilet. Gashaard. LCD-tv, home cinema set, afwasmachine, vloerverwarming, combimagnetron / oven, terras (met verwarming), bediening, schoonmaak en opruim service, Nespresso-koffiezetapparaat, design meubilair, 100 Mbit fast internet en een extra gastenruimte. Maximaal 9 auto’s kunnen voor uw vrijstaande boerderij geparkeerd worden of u kunt gebruik maken van valet Parking.  Uiteraard zijn alle diensten 24/7 beschikbaar', 9),
		(36, 4, 'Zeer grote (en lange) vakantiewoning (Opp. 18000m2) voor grote groepen. Deze  vakantievilla behoord tot de meest bijzondere gebouwen van ons park. Door de lengte van de villa ervaart u een extra ruimtelijk gevoel. Zeer geschikt als u met uw vrienden of gehele familie graag bij elkaar bent.  Er zijn binnen u villa twee golfslagbaden , een theater, een bioscoop en een door Erich zu Putlitz ontworpen feestzaal met veel zitplaatsen. Aan een kade is ruimte om uw eigen boot af te meren. ', 9),




	) as S (id, [type], bio, resortid) on T.id = S.id
when matched then
	update set 
		[type] = S.[type],
		bio = S.bio,
		resortid = S.resortid
when not matched by target then
	insert (id, [type], bio, resortid)
	values (id, [type], bio, resortid)
;

set identity_insert [TYPE] off