CREATE TABLE [dbo].[ACCOMODATIEFACILITEIT]
(
	[id] INT NOT NULL CONSTRAINT [PK_ACCOMODATIEFACILITEIT] PRIMARY KEY IDENTITY, 
    [faciliteit] NVARCHAR(50) NULL, 
	[accomodatieid] INT NOT NULL CONSTRAINT [FK_ACCOMODATIEFACILITEIT_ACCOMODATIE] FOREIGN KEY REFERENCES [ACCOMODATIE]([id])
)
