CREATE TABLE [dbo].[ACCOMODATIE]
(
	[id] INT NOT NULL CONSTRAINT [PK_ACCOMODATIE] PRIMARY KEY IDENTITY, 
	[oppervlakte] NVARCHAR(50) NULL,
	[slaapkamers] INT NULL,
	[autos] INT NULL,
	[typeid] INT NOT NULL CONSTRAINT [FK_ACCOMODATIE_TYPE] FOREIGN KEY REFERENCES [TYPE]([id])
)
