CREATE TABLE [dbo].[ADRES]
(
	[id] INT NOT NULL CONSTRAINT [PK_ADRES] PRIMARY KEY IDENTITY, 
    [land] NVARCHAR(50) NULL, 
    [stad] NVARCHAR(50) NULL, 
    [provincie] NVARCHAR(50) NULL, 
    [straat] NVARCHAR(50) NULL, 
    [postcode] NVARCHAR(50) NULL, 
    [telefoonnummer] INT NULL, 
    [email] NVARCHAR(50) NULL,
	[gebruikerid] INT NOT NULL CONSTRAINT [FK_ADRES_GEBRUIKER] FOREIGN KEY REFERENCES [GEBRUIKER]([id]),
	[resortid] INT NOT NULL CONSTRAINT [FK_ADRES_RESORT] FOREIGN KEY REFERENCES [RESORT]([id])
)
