CREATE TABLE [dbo].[DIENST]
(
	[id] INT NOT NULL CONSTRAINT [PK_DIENST] PRIMARY KEY IDENTITY, 
    [dienst] NVARCHAR(50) NULL, 
    [zorg] NVARCHAR(50) NULL,
	[resortid] INT NOT NULL CONSTRAINT [FK_DIENST_RESORT] FOREIGN KEY REFERENCES [RESORT]([id])
)
