CREATE TABLE [dbo].[FACILITEIT]
(
	[id] INT NOT NULL CONSTRAINT [PK_FACILITEIT] PRIMARY KEY IDENTITY, 
    [faciliteit] NVARCHAR(50) NULL,
	[resortid] INT NOT NULL CONSTRAINT [FK_FACILITEIT_RESORT] FOREIGN KEY REFERENCES [RESORT]([id])
)
