CREATE TABLE [dbo].[RESERVATIE]
(
	[id] INT NOT NULL CONSTRAINT [PK_RESERVATIE] PRIMARY KEY IDENTITY, 
    [datum] DATE NULL, 
    [start] DATE NULL, 
    [eind] DATE NULL,
	[gebruikerid] INT NOT NULL CONSTRAINT [FK_RESERVATIE_GEBRUIKER] FOREIGN KEY REFERENCES [GEBRUIKER]([id]), 
	[resortid] INT NOT NULL CONSTRAINT [FK_RESERVATIE_RESORT] FOREIGN KEY REFERENCES [RESORT]([id]),
	[accomodatieid] INT NOT NULL CONSTRAINT [FK_RESERVATIE_ACCOMODATIE] FOREIGN KEY REFERENCES [ACCOMODATIE]([id]),
	[dienstid] INT NOT NULL CONSTRAINT [FK_RESERVATIE_DIENST] FOREIGN KEY REFERENCES [DIENST]([id])
)
